// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_326 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_reference_V_3_15_18_reload,
        local_reference_V_2_15_18_reload,
        local_reference_V_1_15_18_reload,
        local_reference_V_0_15_18_reload,
        local_reference_V_3_14_18_reload,
        local_reference_V_2_14_18_reload,
        local_reference_V_1_14_18_reload,
        local_reference_V_0_14_18_reload,
        local_reference_V_3_13_18_reload,
        local_reference_V_2_13_18_reload,
        local_reference_V_1_13_18_reload,
        local_reference_V_0_13_18_reload,
        local_reference_V_3_12_18_reload,
        local_reference_V_2_12_18_reload,
        local_reference_V_1_12_18_reload,
        local_reference_V_0_12_18_reload,
        local_reference_V_3_11_18_reload,
        local_reference_V_2_11_18_reload,
        local_reference_V_1_11_18_reload,
        local_reference_V_0_11_18_reload,
        local_reference_V_3_10_18_reload,
        local_reference_V_2_10_18_reload,
        local_reference_V_1_10_18_reload,
        local_reference_V_0_10_18_reload,
        local_reference_V_3_9_18_reload,
        local_reference_V_2_9_18_reload,
        local_reference_V_1_9_18_reload,
        local_reference_V_0_9_18_reload,
        local_reference_V_3_8_18_reload,
        local_reference_V_2_8_18_reload,
        local_reference_V_1_8_18_reload,
        local_reference_V_0_8_18_reload,
        local_reference_V_3_7_18_reload,
        local_reference_V_2_7_18_reload,
        local_reference_V_1_7_18_reload,
        local_reference_V_0_7_18_reload,
        local_reference_V_3_6_18_reload,
        local_reference_V_2_6_18_reload,
        local_reference_V_1_6_18_reload,
        local_reference_V_0_6_18_reload,
        local_reference_V_3_5_18_reload,
        local_reference_V_2_5_18_reload,
        local_reference_V_1_5_18_reload,
        local_reference_V_0_5_18_reload,
        local_reference_V_3_4_18_reload,
        local_reference_V_2_4_18_reload,
        local_reference_V_1_4_18_reload,
        local_reference_V_0_4_18_reload,
        local_reference_V_3_3_18_reload,
        local_reference_V_2_3_18_reload,
        local_reference_V_1_3_18_reload,
        local_reference_V_0_3_18_reload,
        local_reference_V_3_2_18_reload,
        local_reference_V_2_2_18_reload,
        local_reference_V_1_2_18_reload,
        local_reference_V_0_2_18_reload,
        local_reference_V_3_1_18_reload,
        local_reference_V_2_1_18_reload,
        local_reference_V_1_1_18_reload,
        local_reference_V_0_1_18_reload,
        local_reference_V_3_18_reload,
        local_reference_V_2_18_reload,
        local_reference_V_1_18_reload,
        local_reference_V_0_18_reload,
        reference_string_comp_3_address0,
        reference_string_comp_3_ce0,
        reference_string_comp_3_q0,
        local_reference_V_3_15_21_out,
        local_reference_V_3_15_21_out_ap_vld,
        local_reference_V_2_15_21_out,
        local_reference_V_2_15_21_out_ap_vld,
        local_reference_V_1_15_21_out,
        local_reference_V_1_15_21_out_ap_vld,
        local_reference_V_0_15_21_out,
        local_reference_V_0_15_21_out_ap_vld,
        local_reference_V_3_14_21_out,
        local_reference_V_3_14_21_out_ap_vld,
        local_reference_V_2_14_21_out,
        local_reference_V_2_14_21_out_ap_vld,
        local_reference_V_1_14_21_out,
        local_reference_V_1_14_21_out_ap_vld,
        local_reference_V_0_14_21_out,
        local_reference_V_0_14_21_out_ap_vld,
        local_reference_V_3_13_21_out,
        local_reference_V_3_13_21_out_ap_vld,
        local_reference_V_2_13_21_out,
        local_reference_V_2_13_21_out_ap_vld,
        local_reference_V_1_13_21_out,
        local_reference_V_1_13_21_out_ap_vld,
        local_reference_V_0_13_21_out,
        local_reference_V_0_13_21_out_ap_vld,
        local_reference_V_3_12_21_out,
        local_reference_V_3_12_21_out_ap_vld,
        local_reference_V_2_12_21_out,
        local_reference_V_2_12_21_out_ap_vld,
        local_reference_V_1_12_21_out,
        local_reference_V_1_12_21_out_ap_vld,
        local_reference_V_0_12_21_out,
        local_reference_V_0_12_21_out_ap_vld,
        local_reference_V_3_11_21_out,
        local_reference_V_3_11_21_out_ap_vld,
        local_reference_V_2_11_21_out,
        local_reference_V_2_11_21_out_ap_vld,
        local_reference_V_1_11_21_out,
        local_reference_V_1_11_21_out_ap_vld,
        local_reference_V_0_11_21_out,
        local_reference_V_0_11_21_out_ap_vld,
        local_reference_V_3_10_21_out,
        local_reference_V_3_10_21_out_ap_vld,
        local_reference_V_2_10_21_out,
        local_reference_V_2_10_21_out_ap_vld,
        local_reference_V_1_10_21_out,
        local_reference_V_1_10_21_out_ap_vld,
        local_reference_V_0_10_21_out,
        local_reference_V_0_10_21_out_ap_vld,
        local_reference_V_3_9_21_out,
        local_reference_V_3_9_21_out_ap_vld,
        local_reference_V_2_9_21_out,
        local_reference_V_2_9_21_out_ap_vld,
        local_reference_V_1_9_21_out,
        local_reference_V_1_9_21_out_ap_vld,
        local_reference_V_0_9_21_out,
        local_reference_V_0_9_21_out_ap_vld,
        local_reference_V_3_8_21_out,
        local_reference_V_3_8_21_out_ap_vld,
        local_reference_V_2_8_21_out,
        local_reference_V_2_8_21_out_ap_vld,
        local_reference_V_1_8_21_out,
        local_reference_V_1_8_21_out_ap_vld,
        local_reference_V_0_8_21_out,
        local_reference_V_0_8_21_out_ap_vld,
        local_reference_V_3_7_21_out,
        local_reference_V_3_7_21_out_ap_vld,
        local_reference_V_2_7_21_out,
        local_reference_V_2_7_21_out_ap_vld,
        local_reference_V_1_7_21_out,
        local_reference_V_1_7_21_out_ap_vld,
        local_reference_V_0_7_21_out,
        local_reference_V_0_7_21_out_ap_vld,
        local_reference_V_3_6_21_out,
        local_reference_V_3_6_21_out_ap_vld,
        local_reference_V_2_6_21_out,
        local_reference_V_2_6_21_out_ap_vld,
        local_reference_V_1_6_21_out,
        local_reference_V_1_6_21_out_ap_vld,
        local_reference_V_0_6_21_out,
        local_reference_V_0_6_21_out_ap_vld,
        local_reference_V_3_5_21_out,
        local_reference_V_3_5_21_out_ap_vld,
        local_reference_V_2_5_21_out,
        local_reference_V_2_5_21_out_ap_vld,
        local_reference_V_1_5_21_out,
        local_reference_V_1_5_21_out_ap_vld,
        local_reference_V_0_5_21_out,
        local_reference_V_0_5_21_out_ap_vld,
        local_reference_V_3_4_21_out,
        local_reference_V_3_4_21_out_ap_vld,
        local_reference_V_2_4_21_out,
        local_reference_V_2_4_21_out_ap_vld,
        local_reference_V_1_4_21_out,
        local_reference_V_1_4_21_out_ap_vld,
        local_reference_V_0_4_21_out,
        local_reference_V_0_4_21_out_ap_vld,
        local_reference_V_3_3_21_out,
        local_reference_V_3_3_21_out_ap_vld,
        local_reference_V_2_3_21_out,
        local_reference_V_2_3_21_out_ap_vld,
        local_reference_V_1_3_21_out,
        local_reference_V_1_3_21_out_ap_vld,
        local_reference_V_0_3_21_out,
        local_reference_V_0_3_21_out_ap_vld,
        local_reference_V_3_2_21_out,
        local_reference_V_3_2_21_out_ap_vld,
        local_reference_V_2_2_21_out,
        local_reference_V_2_2_21_out_ap_vld,
        local_reference_V_1_2_21_out,
        local_reference_V_1_2_21_out_ap_vld,
        local_reference_V_0_2_21_out,
        local_reference_V_0_2_21_out_ap_vld,
        local_reference_V_3_1_21_out,
        local_reference_V_3_1_21_out_ap_vld,
        local_reference_V_2_1_21_out,
        local_reference_V_2_1_21_out_ap_vld,
        local_reference_V_1_1_21_out,
        local_reference_V_1_1_21_out_ap_vld,
        local_reference_V_0_1_21_out,
        local_reference_V_0_1_21_out_ap_vld,
        local_reference_V_3_21_out,
        local_reference_V_3_21_out_ap_vld,
        local_reference_V_2_21_out,
        local_reference_V_2_21_out_ap_vld,
        local_reference_V_1_21_out,
        local_reference_V_1_21_out_ap_vld,
        local_reference_V_0_21_out,
        local_reference_V_0_21_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] local_reference_V_3_15_18_reload;
input  [1:0] local_reference_V_2_15_18_reload;
input  [1:0] local_reference_V_1_15_18_reload;
input  [1:0] local_reference_V_0_15_18_reload;
input  [1:0] local_reference_V_3_14_18_reload;
input  [1:0] local_reference_V_2_14_18_reload;
input  [1:0] local_reference_V_1_14_18_reload;
input  [1:0] local_reference_V_0_14_18_reload;
input  [1:0] local_reference_V_3_13_18_reload;
input  [1:0] local_reference_V_2_13_18_reload;
input  [1:0] local_reference_V_1_13_18_reload;
input  [1:0] local_reference_V_0_13_18_reload;
input  [1:0] local_reference_V_3_12_18_reload;
input  [1:0] local_reference_V_2_12_18_reload;
input  [1:0] local_reference_V_1_12_18_reload;
input  [1:0] local_reference_V_0_12_18_reload;
input  [1:0] local_reference_V_3_11_18_reload;
input  [1:0] local_reference_V_2_11_18_reload;
input  [1:0] local_reference_V_1_11_18_reload;
input  [1:0] local_reference_V_0_11_18_reload;
input  [1:0] local_reference_V_3_10_18_reload;
input  [1:0] local_reference_V_2_10_18_reload;
input  [1:0] local_reference_V_1_10_18_reload;
input  [1:0] local_reference_V_0_10_18_reload;
input  [1:0] local_reference_V_3_9_18_reload;
input  [1:0] local_reference_V_2_9_18_reload;
input  [1:0] local_reference_V_1_9_18_reload;
input  [1:0] local_reference_V_0_9_18_reload;
input  [1:0] local_reference_V_3_8_18_reload;
input  [1:0] local_reference_V_2_8_18_reload;
input  [1:0] local_reference_V_1_8_18_reload;
input  [1:0] local_reference_V_0_8_18_reload;
input  [1:0] local_reference_V_3_7_18_reload;
input  [1:0] local_reference_V_2_7_18_reload;
input  [1:0] local_reference_V_1_7_18_reload;
input  [1:0] local_reference_V_0_7_18_reload;
input  [1:0] local_reference_V_3_6_18_reload;
input  [1:0] local_reference_V_2_6_18_reload;
input  [1:0] local_reference_V_1_6_18_reload;
input  [1:0] local_reference_V_0_6_18_reload;
input  [1:0] local_reference_V_3_5_18_reload;
input  [1:0] local_reference_V_2_5_18_reload;
input  [1:0] local_reference_V_1_5_18_reload;
input  [1:0] local_reference_V_0_5_18_reload;
input  [1:0] local_reference_V_3_4_18_reload;
input  [1:0] local_reference_V_2_4_18_reload;
input  [1:0] local_reference_V_1_4_18_reload;
input  [1:0] local_reference_V_0_4_18_reload;
input  [1:0] local_reference_V_3_3_18_reload;
input  [1:0] local_reference_V_2_3_18_reload;
input  [1:0] local_reference_V_1_3_18_reload;
input  [1:0] local_reference_V_0_3_18_reload;
input  [1:0] local_reference_V_3_2_18_reload;
input  [1:0] local_reference_V_2_2_18_reload;
input  [1:0] local_reference_V_1_2_18_reload;
input  [1:0] local_reference_V_0_2_18_reload;
input  [1:0] local_reference_V_3_1_18_reload;
input  [1:0] local_reference_V_2_1_18_reload;
input  [1:0] local_reference_V_1_1_18_reload;
input  [1:0] local_reference_V_0_1_18_reload;
input  [1:0] local_reference_V_3_18_reload;
input  [1:0] local_reference_V_2_18_reload;
input  [1:0] local_reference_V_1_18_reload;
input  [1:0] local_reference_V_0_18_reload;
output  [6:0] reference_string_comp_3_address0;
output   reference_string_comp_3_ce0;
input  [1:0] reference_string_comp_3_q0;
output  [1:0] local_reference_V_3_15_21_out;
output   local_reference_V_3_15_21_out_ap_vld;
output  [1:0] local_reference_V_2_15_21_out;
output   local_reference_V_2_15_21_out_ap_vld;
output  [1:0] local_reference_V_1_15_21_out;
output   local_reference_V_1_15_21_out_ap_vld;
output  [1:0] local_reference_V_0_15_21_out;
output   local_reference_V_0_15_21_out_ap_vld;
output  [1:0] local_reference_V_3_14_21_out;
output   local_reference_V_3_14_21_out_ap_vld;
output  [1:0] local_reference_V_2_14_21_out;
output   local_reference_V_2_14_21_out_ap_vld;
output  [1:0] local_reference_V_1_14_21_out;
output   local_reference_V_1_14_21_out_ap_vld;
output  [1:0] local_reference_V_0_14_21_out;
output   local_reference_V_0_14_21_out_ap_vld;
output  [1:0] local_reference_V_3_13_21_out;
output   local_reference_V_3_13_21_out_ap_vld;
output  [1:0] local_reference_V_2_13_21_out;
output   local_reference_V_2_13_21_out_ap_vld;
output  [1:0] local_reference_V_1_13_21_out;
output   local_reference_V_1_13_21_out_ap_vld;
output  [1:0] local_reference_V_0_13_21_out;
output   local_reference_V_0_13_21_out_ap_vld;
output  [1:0] local_reference_V_3_12_21_out;
output   local_reference_V_3_12_21_out_ap_vld;
output  [1:0] local_reference_V_2_12_21_out;
output   local_reference_V_2_12_21_out_ap_vld;
output  [1:0] local_reference_V_1_12_21_out;
output   local_reference_V_1_12_21_out_ap_vld;
output  [1:0] local_reference_V_0_12_21_out;
output   local_reference_V_0_12_21_out_ap_vld;
output  [1:0] local_reference_V_3_11_21_out;
output   local_reference_V_3_11_21_out_ap_vld;
output  [1:0] local_reference_V_2_11_21_out;
output   local_reference_V_2_11_21_out_ap_vld;
output  [1:0] local_reference_V_1_11_21_out;
output   local_reference_V_1_11_21_out_ap_vld;
output  [1:0] local_reference_V_0_11_21_out;
output   local_reference_V_0_11_21_out_ap_vld;
output  [1:0] local_reference_V_3_10_21_out;
output   local_reference_V_3_10_21_out_ap_vld;
output  [1:0] local_reference_V_2_10_21_out;
output   local_reference_V_2_10_21_out_ap_vld;
output  [1:0] local_reference_V_1_10_21_out;
output   local_reference_V_1_10_21_out_ap_vld;
output  [1:0] local_reference_V_0_10_21_out;
output   local_reference_V_0_10_21_out_ap_vld;
output  [1:0] local_reference_V_3_9_21_out;
output   local_reference_V_3_9_21_out_ap_vld;
output  [1:0] local_reference_V_2_9_21_out;
output   local_reference_V_2_9_21_out_ap_vld;
output  [1:0] local_reference_V_1_9_21_out;
output   local_reference_V_1_9_21_out_ap_vld;
output  [1:0] local_reference_V_0_9_21_out;
output   local_reference_V_0_9_21_out_ap_vld;
output  [1:0] local_reference_V_3_8_21_out;
output   local_reference_V_3_8_21_out_ap_vld;
output  [1:0] local_reference_V_2_8_21_out;
output   local_reference_V_2_8_21_out_ap_vld;
output  [1:0] local_reference_V_1_8_21_out;
output   local_reference_V_1_8_21_out_ap_vld;
output  [1:0] local_reference_V_0_8_21_out;
output   local_reference_V_0_8_21_out_ap_vld;
output  [1:0] local_reference_V_3_7_21_out;
output   local_reference_V_3_7_21_out_ap_vld;
output  [1:0] local_reference_V_2_7_21_out;
output   local_reference_V_2_7_21_out_ap_vld;
output  [1:0] local_reference_V_1_7_21_out;
output   local_reference_V_1_7_21_out_ap_vld;
output  [1:0] local_reference_V_0_7_21_out;
output   local_reference_V_0_7_21_out_ap_vld;
output  [1:0] local_reference_V_3_6_21_out;
output   local_reference_V_3_6_21_out_ap_vld;
output  [1:0] local_reference_V_2_6_21_out;
output   local_reference_V_2_6_21_out_ap_vld;
output  [1:0] local_reference_V_1_6_21_out;
output   local_reference_V_1_6_21_out_ap_vld;
output  [1:0] local_reference_V_0_6_21_out;
output   local_reference_V_0_6_21_out_ap_vld;
output  [1:0] local_reference_V_3_5_21_out;
output   local_reference_V_3_5_21_out_ap_vld;
output  [1:0] local_reference_V_2_5_21_out;
output   local_reference_V_2_5_21_out_ap_vld;
output  [1:0] local_reference_V_1_5_21_out;
output   local_reference_V_1_5_21_out_ap_vld;
output  [1:0] local_reference_V_0_5_21_out;
output   local_reference_V_0_5_21_out_ap_vld;
output  [1:0] local_reference_V_3_4_21_out;
output   local_reference_V_3_4_21_out_ap_vld;
output  [1:0] local_reference_V_2_4_21_out;
output   local_reference_V_2_4_21_out_ap_vld;
output  [1:0] local_reference_V_1_4_21_out;
output   local_reference_V_1_4_21_out_ap_vld;
output  [1:0] local_reference_V_0_4_21_out;
output   local_reference_V_0_4_21_out_ap_vld;
output  [1:0] local_reference_V_3_3_21_out;
output   local_reference_V_3_3_21_out_ap_vld;
output  [1:0] local_reference_V_2_3_21_out;
output   local_reference_V_2_3_21_out_ap_vld;
output  [1:0] local_reference_V_1_3_21_out;
output   local_reference_V_1_3_21_out_ap_vld;
output  [1:0] local_reference_V_0_3_21_out;
output   local_reference_V_0_3_21_out_ap_vld;
output  [1:0] local_reference_V_3_2_21_out;
output   local_reference_V_3_2_21_out_ap_vld;
output  [1:0] local_reference_V_2_2_21_out;
output   local_reference_V_2_2_21_out_ap_vld;
output  [1:0] local_reference_V_1_2_21_out;
output   local_reference_V_1_2_21_out_ap_vld;
output  [1:0] local_reference_V_0_2_21_out;
output   local_reference_V_0_2_21_out_ap_vld;
output  [1:0] local_reference_V_3_1_21_out;
output   local_reference_V_3_1_21_out_ap_vld;
output  [1:0] local_reference_V_2_1_21_out;
output   local_reference_V_2_1_21_out_ap_vld;
output  [1:0] local_reference_V_1_1_21_out;
output   local_reference_V_1_1_21_out_ap_vld;
output  [1:0] local_reference_V_0_1_21_out;
output   local_reference_V_0_1_21_out_ap_vld;
output  [1:0] local_reference_V_3_21_out;
output   local_reference_V_3_21_out_ap_vld;
output  [1:0] local_reference_V_2_21_out;
output   local_reference_V_2_21_out_ap_vld;
output  [1:0] local_reference_V_1_21_out;
output   local_reference_V_1_21_out_ap_vld;
output  [1:0] local_reference_V_0_21_out;
output   local_reference_V_0_21_out_ap_vld;

reg ap_idle;
reg reference_string_comp_3_ce0;
reg local_reference_V_3_15_21_out_ap_vld;
reg local_reference_V_2_15_21_out_ap_vld;
reg local_reference_V_1_15_21_out_ap_vld;
reg local_reference_V_0_15_21_out_ap_vld;
reg local_reference_V_3_14_21_out_ap_vld;
reg local_reference_V_2_14_21_out_ap_vld;
reg local_reference_V_1_14_21_out_ap_vld;
reg local_reference_V_0_14_21_out_ap_vld;
reg local_reference_V_3_13_21_out_ap_vld;
reg local_reference_V_2_13_21_out_ap_vld;
reg local_reference_V_1_13_21_out_ap_vld;
reg local_reference_V_0_13_21_out_ap_vld;
reg local_reference_V_3_12_21_out_ap_vld;
reg local_reference_V_2_12_21_out_ap_vld;
reg local_reference_V_1_12_21_out_ap_vld;
reg local_reference_V_0_12_21_out_ap_vld;
reg local_reference_V_3_11_21_out_ap_vld;
reg local_reference_V_2_11_21_out_ap_vld;
reg local_reference_V_1_11_21_out_ap_vld;
reg local_reference_V_0_11_21_out_ap_vld;
reg local_reference_V_3_10_21_out_ap_vld;
reg local_reference_V_2_10_21_out_ap_vld;
reg local_reference_V_1_10_21_out_ap_vld;
reg local_reference_V_0_10_21_out_ap_vld;
reg local_reference_V_3_9_21_out_ap_vld;
reg local_reference_V_2_9_21_out_ap_vld;
reg local_reference_V_1_9_21_out_ap_vld;
reg local_reference_V_0_9_21_out_ap_vld;
reg local_reference_V_3_8_21_out_ap_vld;
reg local_reference_V_2_8_21_out_ap_vld;
reg local_reference_V_1_8_21_out_ap_vld;
reg local_reference_V_0_8_21_out_ap_vld;
reg local_reference_V_3_7_21_out_ap_vld;
reg local_reference_V_2_7_21_out_ap_vld;
reg local_reference_V_1_7_21_out_ap_vld;
reg local_reference_V_0_7_21_out_ap_vld;
reg local_reference_V_3_6_21_out_ap_vld;
reg local_reference_V_2_6_21_out_ap_vld;
reg local_reference_V_1_6_21_out_ap_vld;
reg local_reference_V_0_6_21_out_ap_vld;
reg local_reference_V_3_5_21_out_ap_vld;
reg local_reference_V_2_5_21_out_ap_vld;
reg local_reference_V_1_5_21_out_ap_vld;
reg local_reference_V_0_5_21_out_ap_vld;
reg local_reference_V_3_4_21_out_ap_vld;
reg local_reference_V_2_4_21_out_ap_vld;
reg local_reference_V_1_4_21_out_ap_vld;
reg local_reference_V_0_4_21_out_ap_vld;
reg local_reference_V_3_3_21_out_ap_vld;
reg local_reference_V_2_3_21_out_ap_vld;
reg local_reference_V_1_3_21_out_ap_vld;
reg local_reference_V_0_3_21_out_ap_vld;
reg local_reference_V_3_2_21_out_ap_vld;
reg local_reference_V_2_2_21_out_ap_vld;
reg local_reference_V_1_2_21_out_ap_vld;
reg local_reference_V_0_2_21_out_ap_vld;
reg local_reference_V_3_1_21_out_ap_vld;
reg local_reference_V_2_1_21_out_ap_vld;
reg local_reference_V_1_1_21_out_ap_vld;
reg local_reference_V_0_1_21_out_ap_vld;
reg local_reference_V_3_21_out_ap_vld;
reg local_reference_V_2_21_out_ap_vld;
reg local_reference_V_1_21_out_ap_vld;
reg local_reference_V_0_21_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln93_fu_1769_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] trunc_ln94_s_reg_2850;
wire   [3:0] trunc_ln94_fu_1802_p1;
reg   [3:0] trunc_ln94_reg_2854;
wire   [63:0] zext_ln94_fu_1787_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_336;
wire   [6:0] add_ln93_fu_1775_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_2;
reg   [1:0] local_reference_V_1_fu_340;
reg   [1:0] local_reference_V_1_21_fu_344;
reg   [1:0] local_reference_V_1_66_fu_348;
reg   [1:0] local_reference_V_1_67_fu_352;
reg   [1:0] local_reference_V_1_68_fu_356;
reg   [1:0] local_reference_V_1_69_fu_360;
reg   [1:0] local_reference_V_1_70_fu_364;
reg   [1:0] local_reference_V_1_71_fu_368;
reg   [1:0] local_reference_V_1_72_fu_372;
reg   [1:0] local_reference_V_1_73_fu_376;
reg   [1:0] local_reference_V_1_74_fu_380;
reg   [1:0] local_reference_V_1_75_fu_384;
reg   [1:0] local_reference_V_1_76_fu_388;
reg   [1:0] local_reference_V_1_77_fu_392;
reg   [1:0] local_reference_V_1_78_fu_396;
reg   [1:0] local_reference_V_1_79_fu_400;
reg   [1:0] local_reference_V_1_80_fu_404;
reg   [1:0] local_reference_V_1_81_fu_408;
reg   [1:0] local_reference_V_1_82_fu_412;
reg   [1:0] local_reference_V_1_83_fu_416;
reg   [1:0] local_reference_V_1_84_fu_420;
reg   [1:0] local_reference_V_1_85_fu_424;
reg   [1:0] local_reference_V_1_86_fu_428;
reg   [1:0] local_reference_V_1_87_fu_432;
reg   [1:0] local_reference_V_1_88_fu_436;
reg   [1:0] local_reference_V_1_89_fu_440;
reg   [1:0] local_reference_V_1_90_fu_444;
reg   [1:0] local_reference_V_1_91_fu_448;
reg   [1:0] local_reference_V_1_92_fu_452;
reg   [1:0] local_reference_V_1_93_fu_456;
reg   [1:0] local_reference_V_1_94_fu_460;
reg   [1:0] local_reference_V_1_95_fu_464;
reg   [1:0] local_reference_V_1_96_fu_468;
reg   [1:0] local_reference_V_1_97_fu_472;
reg   [1:0] local_reference_V_1_98_fu_476;
reg   [1:0] local_reference_V_1_99_fu_480;
reg   [1:0] local_reference_V_1_100_fu_484;
reg   [1:0] local_reference_V_1_101_fu_488;
reg   [1:0] local_reference_V_1_102_fu_492;
reg   [1:0] local_reference_V_1_103_fu_496;
reg   [1:0] local_reference_V_1_104_fu_500;
reg   [1:0] local_reference_V_1_105_fu_504;
reg   [1:0] local_reference_V_1_106_fu_508;
reg   [1:0] local_reference_V_1_107_fu_512;
reg   [1:0] local_reference_V_1_108_fu_516;
reg   [1:0] local_reference_V_1_109_fu_520;
reg   [1:0] local_reference_V_1_110_fu_524;
reg   [1:0] local_reference_V_1_111_fu_528;
reg   [1:0] local_reference_V_1_112_fu_532;
reg   [1:0] local_reference_V_1_113_fu_536;
reg   [1:0] local_reference_V_1_114_fu_540;
reg   [1:0] local_reference_V_1_115_fu_544;
reg   [1:0] local_reference_V_1_116_fu_548;
reg   [1:0] local_reference_V_1_117_fu_552;
reg   [1:0] local_reference_V_1_118_fu_556;
reg   [1:0] local_reference_V_1_119_fu_560;
reg   [1:0] local_reference_V_1_120_fu_564;
reg   [1:0] local_reference_V_1_121_fu_568;
reg   [1:0] local_reference_V_1_122_fu_572;
reg   [1:0] local_reference_V_1_123_fu_576;
reg   [1:0] local_reference_V_1_124_fu_580;
reg   [1:0] local_reference_V_1_125_fu_584;
reg   [1:0] local_reference_V_1_126_fu_588;
reg   [1:0] local_reference_V_1_127_fu_592;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] xor_ln94_fu_1781_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_894;
reg    ap_condition_897;
reg    ap_condition_900;
reg    ap_condition_903;
reg    ap_condition_906;
reg    ap_condition_909;
reg    ap_condition_912;
reg    ap_condition_915;
reg    ap_condition_918;
reg    ap_condition_921;
reg    ap_condition_924;
reg    ap_condition_927;
reg    ap_condition_930;
reg    ap_condition_933;
reg    ap_condition_936;
reg    ap_condition_939;
reg    ap_condition_942;
reg    ap_condition_945;
reg    ap_condition_948;
reg    ap_condition_951;
reg    ap_condition_954;
reg    ap_condition_957;
reg    ap_condition_960;
reg    ap_condition_963;
reg    ap_condition_966;
reg    ap_condition_969;
reg    ap_condition_972;
reg    ap_condition_975;
reg    ap_condition_978;
reg    ap_condition_981;
reg    ap_condition_984;
reg    ap_condition_987;
reg    ap_condition_990;
reg    ap_condition_993;
reg    ap_condition_996;
reg    ap_condition_999;
reg    ap_condition_1002;
reg    ap_condition_1005;
reg    ap_condition_1008;
reg    ap_condition_1011;
reg    ap_condition_1014;
reg    ap_condition_1017;
reg    ap_condition_1020;
reg    ap_condition_1023;
reg    ap_condition_1026;
reg    ap_condition_1029;
reg    ap_condition_1032;
reg    ap_condition_1035;
reg    ap_condition_1038;
reg    ap_condition_1041;
reg    ap_condition_1044;
reg    ap_condition_1047;
reg    ap_condition_1050;
reg    ap_condition_1053;
reg    ap_condition_1056;
reg    ap_condition_1059;
reg    ap_condition_1062;
reg    ap_condition_1065;
reg    ap_condition_1068;
reg    ap_condition_1071;
reg    ap_condition_1074;
reg    ap_condition_1077;
reg    ap_condition_1080;
reg    ap_condition_1083;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

seq_align_multiple_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln93_fu_1769_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_336 <= add_ln93_fu_1775_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_336 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_100_fu_484 <= local_reference_V_0_9_18_reload;
        end else if ((1'b1 == ap_condition_894)) begin
            local_reference_V_1_100_fu_484 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_101_fu_488 <= local_reference_V_1_9_18_reload;
        end else if ((1'b1 == ap_condition_897)) begin
            local_reference_V_1_101_fu_488 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_102_fu_492 <= local_reference_V_2_9_18_reload;
        end else if ((1'b1 == ap_condition_900)) begin
            local_reference_V_1_102_fu_492 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_103_fu_496 <= local_reference_V_3_9_18_reload;
        end else if ((1'b1 == ap_condition_903)) begin
            local_reference_V_1_103_fu_496 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_104_fu_500 <= local_reference_V_0_10_18_reload;
        end else if ((1'b1 == ap_condition_906)) begin
            local_reference_V_1_104_fu_500 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_105_fu_504 <= local_reference_V_1_10_18_reload;
        end else if ((1'b1 == ap_condition_909)) begin
            local_reference_V_1_105_fu_504 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_106_fu_508 <= local_reference_V_2_10_18_reload;
        end else if ((1'b1 == ap_condition_912)) begin
            local_reference_V_1_106_fu_508 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_107_fu_512 <= local_reference_V_3_10_18_reload;
        end else if ((1'b1 == ap_condition_915)) begin
            local_reference_V_1_107_fu_512 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_108_fu_516 <= local_reference_V_0_11_18_reload;
        end else if ((1'b1 == ap_condition_918)) begin
            local_reference_V_1_108_fu_516 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_109_fu_520 <= local_reference_V_1_11_18_reload;
        end else if ((1'b1 == ap_condition_921)) begin
            local_reference_V_1_109_fu_520 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_110_fu_524 <= local_reference_V_2_11_18_reload;
        end else if ((1'b1 == ap_condition_924)) begin
            local_reference_V_1_110_fu_524 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_111_fu_528 <= local_reference_V_3_11_18_reload;
        end else if ((1'b1 == ap_condition_927)) begin
            local_reference_V_1_111_fu_528 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_112_fu_532 <= local_reference_V_0_12_18_reload;
        end else if ((1'b1 == ap_condition_930)) begin
            local_reference_V_1_112_fu_532 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_113_fu_536 <= local_reference_V_1_12_18_reload;
        end else if ((1'b1 == ap_condition_933)) begin
            local_reference_V_1_113_fu_536 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_114_fu_540 <= local_reference_V_2_12_18_reload;
        end else if ((1'b1 == ap_condition_936)) begin
            local_reference_V_1_114_fu_540 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_115_fu_544 <= local_reference_V_3_12_18_reload;
        end else if ((1'b1 == ap_condition_939)) begin
            local_reference_V_1_115_fu_544 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_116_fu_548 <= local_reference_V_0_13_18_reload;
        end else if ((1'b1 == ap_condition_942)) begin
            local_reference_V_1_116_fu_548 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_117_fu_552 <= local_reference_V_1_13_18_reload;
        end else if ((1'b1 == ap_condition_945)) begin
            local_reference_V_1_117_fu_552 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_118_fu_556 <= local_reference_V_2_13_18_reload;
        end else if ((1'b1 == ap_condition_948)) begin
            local_reference_V_1_118_fu_556 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_119_fu_560 <= local_reference_V_3_13_18_reload;
        end else if ((1'b1 == ap_condition_951)) begin
            local_reference_V_1_119_fu_560 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_120_fu_564 <= local_reference_V_0_14_18_reload;
        end else if ((1'b1 == ap_condition_954)) begin
            local_reference_V_1_120_fu_564 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_121_fu_568 <= local_reference_V_1_14_18_reload;
        end else if ((1'b1 == ap_condition_957)) begin
            local_reference_V_1_121_fu_568 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_122_fu_572 <= local_reference_V_2_14_18_reload;
        end else if ((1'b1 == ap_condition_960)) begin
            local_reference_V_1_122_fu_572 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_123_fu_576 <= local_reference_V_3_14_18_reload;
        end else if ((1'b1 == ap_condition_963)) begin
            local_reference_V_1_123_fu_576 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_124_fu_580 <= local_reference_V_0_15_18_reload;
        end else if ((1'b1 == ap_condition_966)) begin
            local_reference_V_1_124_fu_580 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_125_fu_584 <= local_reference_V_1_15_18_reload;
        end else if ((1'b1 == ap_condition_969)) begin
            local_reference_V_1_125_fu_584 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_126_fu_588 <= local_reference_V_2_15_18_reload;
        end else if ((1'b1 == ap_condition_972)) begin
            local_reference_V_1_126_fu_588 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_127_fu_592 <= local_reference_V_3_15_18_reload;
        end else if ((1'b1 == ap_condition_975)) begin
            local_reference_V_1_127_fu_592 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_21_fu_344 <= local_reference_V_1_18_reload;
        end else if ((1'b1 == ap_condition_978)) begin
            local_reference_V_1_21_fu_344 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_66_fu_348 <= local_reference_V_2_18_reload;
        end else if ((1'b1 == ap_condition_981)) begin
            local_reference_V_1_66_fu_348 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_67_fu_352 <= local_reference_V_3_18_reload;
        end else if ((1'b1 == ap_condition_984)) begin
            local_reference_V_1_67_fu_352 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_68_fu_356 <= local_reference_V_0_1_18_reload;
        end else if ((1'b1 == ap_condition_987)) begin
            local_reference_V_1_68_fu_356 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_69_fu_360 <= local_reference_V_1_1_18_reload;
        end else if ((1'b1 == ap_condition_990)) begin
            local_reference_V_1_69_fu_360 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_70_fu_364 <= local_reference_V_2_1_18_reload;
        end else if ((1'b1 == ap_condition_993)) begin
            local_reference_V_1_70_fu_364 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_71_fu_368 <= local_reference_V_3_1_18_reload;
        end else if ((1'b1 == ap_condition_996)) begin
            local_reference_V_1_71_fu_368 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_72_fu_372 <= local_reference_V_0_2_18_reload;
        end else if ((1'b1 == ap_condition_999)) begin
            local_reference_V_1_72_fu_372 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_73_fu_376 <= local_reference_V_1_2_18_reload;
        end else if ((1'b1 == ap_condition_1002)) begin
            local_reference_V_1_73_fu_376 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_74_fu_380 <= local_reference_V_2_2_18_reload;
        end else if ((1'b1 == ap_condition_1005)) begin
            local_reference_V_1_74_fu_380 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_75_fu_384 <= local_reference_V_3_2_18_reload;
        end else if ((1'b1 == ap_condition_1008)) begin
            local_reference_V_1_75_fu_384 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_76_fu_388 <= local_reference_V_0_3_18_reload;
        end else if ((1'b1 == ap_condition_1011)) begin
            local_reference_V_1_76_fu_388 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_77_fu_392 <= local_reference_V_1_3_18_reload;
        end else if ((1'b1 == ap_condition_1014)) begin
            local_reference_V_1_77_fu_392 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_78_fu_396 <= local_reference_V_2_3_18_reload;
        end else if ((1'b1 == ap_condition_1017)) begin
            local_reference_V_1_78_fu_396 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_79_fu_400 <= local_reference_V_3_3_18_reload;
        end else if ((1'b1 == ap_condition_1020)) begin
            local_reference_V_1_79_fu_400 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_80_fu_404 <= local_reference_V_0_4_18_reload;
        end else if ((1'b1 == ap_condition_1023)) begin
            local_reference_V_1_80_fu_404 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_81_fu_408 <= local_reference_V_1_4_18_reload;
        end else if ((1'b1 == ap_condition_1026)) begin
            local_reference_V_1_81_fu_408 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_82_fu_412 <= local_reference_V_2_4_18_reload;
        end else if ((1'b1 == ap_condition_1029)) begin
            local_reference_V_1_82_fu_412 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_83_fu_416 <= local_reference_V_3_4_18_reload;
        end else if ((1'b1 == ap_condition_1032)) begin
            local_reference_V_1_83_fu_416 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_84_fu_420 <= local_reference_V_0_5_18_reload;
        end else if ((1'b1 == ap_condition_1035)) begin
            local_reference_V_1_84_fu_420 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_85_fu_424 <= local_reference_V_1_5_18_reload;
        end else if ((1'b1 == ap_condition_1038)) begin
            local_reference_V_1_85_fu_424 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_86_fu_428 <= local_reference_V_2_5_18_reload;
        end else if ((1'b1 == ap_condition_1041)) begin
            local_reference_V_1_86_fu_428 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_87_fu_432 <= local_reference_V_3_5_18_reload;
        end else if ((1'b1 == ap_condition_1044)) begin
            local_reference_V_1_87_fu_432 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_88_fu_436 <= local_reference_V_0_6_18_reload;
        end else if ((1'b1 == ap_condition_1047)) begin
            local_reference_V_1_88_fu_436 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_89_fu_440 <= local_reference_V_1_6_18_reload;
        end else if ((1'b1 == ap_condition_1050)) begin
            local_reference_V_1_89_fu_440 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_90_fu_444 <= local_reference_V_2_6_18_reload;
        end else if ((1'b1 == ap_condition_1053)) begin
            local_reference_V_1_90_fu_444 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_91_fu_448 <= local_reference_V_3_6_18_reload;
        end else if ((1'b1 == ap_condition_1056)) begin
            local_reference_V_1_91_fu_448 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_92_fu_452 <= local_reference_V_0_7_18_reload;
        end else if ((1'b1 == ap_condition_1059)) begin
            local_reference_V_1_92_fu_452 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_93_fu_456 <= local_reference_V_1_7_18_reload;
        end else if ((1'b1 == ap_condition_1062)) begin
            local_reference_V_1_93_fu_456 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_94_fu_460 <= local_reference_V_2_7_18_reload;
        end else if ((1'b1 == ap_condition_1065)) begin
            local_reference_V_1_94_fu_460 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_95_fu_464 <= local_reference_V_3_7_18_reload;
        end else if ((1'b1 == ap_condition_1068)) begin
            local_reference_V_1_95_fu_464 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_96_fu_468 <= local_reference_V_0_8_18_reload;
        end else if ((1'b1 == ap_condition_1071)) begin
            local_reference_V_1_96_fu_468 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_97_fu_472 <= local_reference_V_1_8_18_reload;
        end else if ((1'b1 == ap_condition_1074)) begin
            local_reference_V_1_97_fu_472 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_98_fu_476 <= local_reference_V_2_8_18_reload;
        end else if ((1'b1 == ap_condition_1077)) begin
            local_reference_V_1_98_fu_476 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_99_fu_480 <= local_reference_V_3_8_18_reload;
        end else if ((1'b1 == ap_condition_1080)) begin
            local_reference_V_1_99_fu_480 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_reference_V_1_fu_340 <= local_reference_V_0_18_reload;
        end else if ((1'b1 == ap_condition_1083)) begin
            local_reference_V_1_fu_340 <= reference_string_comp_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln94_reg_2854 <= trunc_ln94_fu_1802_p1;
        trunc_ln94_s_reg_2850 <= {{ap_sig_allocacmp_i_2[5:4]}};
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_336;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_10_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_10_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_11_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_11_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_12_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_12_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_13_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_13_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_14_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_14_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_15_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_15_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_1_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_2_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_2_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_3_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_3_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_4_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_4_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_5_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_5_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_6_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_6_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_7_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_7_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_8_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_8_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_0_9_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_0_9_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_10_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_10_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_11_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_11_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_12_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_12_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_13_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_13_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_14_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_14_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_15_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_15_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_1_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_2_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_2_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_3_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_3_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_4_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_4_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_5_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_5_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_6_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_6_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_7_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_7_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_8_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_8_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_1_9_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_1_9_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_10_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_10_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_11_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_11_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_12_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_12_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_13_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_13_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_14_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_14_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_15_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_15_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_1_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_2_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_2_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_3_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_3_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_4_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_4_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_5_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_5_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_6_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_6_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_7_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_7_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_8_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_8_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_2_9_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_2_9_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_10_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_10_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_11_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_11_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_12_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_12_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_13_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_13_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_14_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_14_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_15_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_15_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_1_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_1_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_2_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_2_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_3_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_3_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_4_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_4_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_5_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_5_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_6_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_6_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_7_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_7_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_8_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_8_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_1769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_reference_V_3_9_21_out_ap_vld = 1'b1;
    end else begin
        local_reference_V_3_9_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reference_string_comp_3_ce0 = 1'b1;
    end else begin
        reference_string_comp_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln93_fu_1775_p2 = (ap_sig_allocacmp_i_2 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1002 = ((trunc_ln94_reg_2854 == 4'd2) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1005 = ((trunc_ln94_reg_2854 == 4'd2) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1008 = ((trunc_ln94_reg_2854 == 4'd2) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1011 = ((trunc_ln94_reg_2854 == 4'd3) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1014 = ((trunc_ln94_reg_2854 == 4'd3) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1017 = ((trunc_ln94_reg_2854 == 4'd3) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1020 = ((trunc_ln94_reg_2854 == 4'd3) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1023 = ((trunc_ln94_reg_2854 == 4'd4) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1026 = ((trunc_ln94_reg_2854 == 4'd4) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1029 = ((trunc_ln94_reg_2854 == 4'd4) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1032 = ((trunc_ln94_reg_2854 == 4'd4) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1035 = ((trunc_ln94_reg_2854 == 4'd5) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1038 = ((trunc_ln94_reg_2854 == 4'd5) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1041 = ((trunc_ln94_reg_2854 == 4'd5) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1044 = ((trunc_ln94_reg_2854 == 4'd5) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1047 = ((trunc_ln94_reg_2854 == 4'd6) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1050 = ((trunc_ln94_reg_2854 == 4'd6) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1053 = ((trunc_ln94_reg_2854 == 4'd6) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1056 = ((trunc_ln94_reg_2854 == 4'd6) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1059 = ((trunc_ln94_reg_2854 == 4'd7) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1062 = ((trunc_ln94_reg_2854 == 4'd7) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1065 = ((trunc_ln94_reg_2854 == 4'd7) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1068 = ((trunc_ln94_reg_2854 == 4'd7) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1071 = ((trunc_ln94_reg_2854 == 4'd8) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1074 = ((trunc_ln94_reg_2854 == 4'd8) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1077 = ((trunc_ln94_reg_2854 == 4'd8) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1080 = ((trunc_ln94_reg_2854 == 4'd8) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_1083 = ((trunc_ln94_reg_2854 == 4'd0) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_894 = ((trunc_ln94_reg_2854 == 4'd9) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_897 = ((trunc_ln94_reg_2854 == 4'd9) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_900 = ((trunc_ln94_reg_2854 == 4'd9) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_903 = ((trunc_ln94_reg_2854 == 4'd9) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_906 = ((trunc_ln94_reg_2854 == 4'd10) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_909 = ((trunc_ln94_reg_2854 == 4'd10) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_912 = ((trunc_ln94_reg_2854 == 4'd10) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_915 = ((trunc_ln94_reg_2854 == 4'd10) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_918 = ((trunc_ln94_reg_2854 == 4'd11) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_921 = ((trunc_ln94_reg_2854 == 4'd11) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_924 = ((trunc_ln94_reg_2854 == 4'd11) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_927 = ((trunc_ln94_reg_2854 == 4'd11) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_930 = ((trunc_ln94_reg_2854 == 4'd12) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_933 = ((trunc_ln94_reg_2854 == 4'd12) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_936 = ((trunc_ln94_reg_2854 == 4'd12) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_939 = ((trunc_ln94_reg_2854 == 4'd12) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_942 = ((trunc_ln94_reg_2854 == 4'd13) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_945 = ((trunc_ln94_reg_2854 == 4'd13) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_948 = ((trunc_ln94_reg_2854 == 4'd13) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_951 = ((trunc_ln94_reg_2854 == 4'd13) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_954 = ((trunc_ln94_reg_2854 == 4'd14) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_957 = ((trunc_ln94_reg_2854 == 4'd14) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_960 = ((trunc_ln94_reg_2854 == 4'd14) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_963 = ((trunc_ln94_reg_2854 == 4'd14) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_966 = ((trunc_ln94_reg_2854 == 4'd15) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_969 = ((trunc_ln94_reg_2854 == 4'd15) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_972 = ((trunc_ln94_reg_2854 == 4'd15) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_975 = ((trunc_ln94_reg_2854 == 4'd15) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_978 = ((trunc_ln94_reg_2854 == 4'd0) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_981 = ((trunc_ln94_reg_2854 == 4'd0) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_984 = ((trunc_ln94_reg_2854 == 4'd0) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_987 = ((trunc_ln94_reg_2854 == 4'd1) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_990 = ((trunc_ln94_reg_2854 == 4'd1) & (trunc_ln94_s_reg_2850 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_993 = ((trunc_ln94_reg_2854 == 4'd1) & (trunc_ln94_s_reg_2850 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_996 = ((trunc_ln94_reg_2854 == 4'd1) & (trunc_ln94_s_reg_2850 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_999 = ((trunc_ln94_reg_2854 == 4'd2) & (trunc_ln94_s_reg_2850 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln93_fu_1769_p2 = ((ap_sig_allocacmp_i_2 == 7'd64) ? 1'b1 : 1'b0);

assign local_reference_V_0_10_21_out = local_reference_V_1_104_fu_500;

assign local_reference_V_0_11_21_out = local_reference_V_1_108_fu_516;

assign local_reference_V_0_12_21_out = local_reference_V_1_112_fu_532;

assign local_reference_V_0_13_21_out = local_reference_V_1_116_fu_548;

assign local_reference_V_0_14_21_out = local_reference_V_1_120_fu_564;

assign local_reference_V_0_15_21_out = local_reference_V_1_124_fu_580;

assign local_reference_V_0_1_21_out = local_reference_V_1_68_fu_356;

assign local_reference_V_0_21_out = local_reference_V_1_fu_340;

assign local_reference_V_0_2_21_out = local_reference_V_1_72_fu_372;

assign local_reference_V_0_3_21_out = local_reference_V_1_76_fu_388;

assign local_reference_V_0_4_21_out = local_reference_V_1_80_fu_404;

assign local_reference_V_0_5_21_out = local_reference_V_1_84_fu_420;

assign local_reference_V_0_6_21_out = local_reference_V_1_88_fu_436;

assign local_reference_V_0_7_21_out = local_reference_V_1_92_fu_452;

assign local_reference_V_0_8_21_out = local_reference_V_1_96_fu_468;

assign local_reference_V_0_9_21_out = local_reference_V_1_100_fu_484;

assign local_reference_V_1_10_21_out = local_reference_V_1_105_fu_504;

assign local_reference_V_1_11_21_out = local_reference_V_1_109_fu_520;

assign local_reference_V_1_12_21_out = local_reference_V_1_113_fu_536;

assign local_reference_V_1_13_21_out = local_reference_V_1_117_fu_552;

assign local_reference_V_1_14_21_out = local_reference_V_1_121_fu_568;

assign local_reference_V_1_15_21_out = local_reference_V_1_125_fu_584;

assign local_reference_V_1_1_21_out = local_reference_V_1_69_fu_360;

assign local_reference_V_1_21_out = local_reference_V_1_21_fu_344;

assign local_reference_V_1_2_21_out = local_reference_V_1_73_fu_376;

assign local_reference_V_1_3_21_out = local_reference_V_1_77_fu_392;

assign local_reference_V_1_4_21_out = local_reference_V_1_81_fu_408;

assign local_reference_V_1_5_21_out = local_reference_V_1_85_fu_424;

assign local_reference_V_1_6_21_out = local_reference_V_1_89_fu_440;

assign local_reference_V_1_7_21_out = local_reference_V_1_93_fu_456;

assign local_reference_V_1_8_21_out = local_reference_V_1_97_fu_472;

assign local_reference_V_1_9_21_out = local_reference_V_1_101_fu_488;

assign local_reference_V_2_10_21_out = local_reference_V_1_106_fu_508;

assign local_reference_V_2_11_21_out = local_reference_V_1_110_fu_524;

assign local_reference_V_2_12_21_out = local_reference_V_1_114_fu_540;

assign local_reference_V_2_13_21_out = local_reference_V_1_118_fu_556;

assign local_reference_V_2_14_21_out = local_reference_V_1_122_fu_572;

assign local_reference_V_2_15_21_out = local_reference_V_1_126_fu_588;

assign local_reference_V_2_1_21_out = local_reference_V_1_70_fu_364;

assign local_reference_V_2_21_out = local_reference_V_1_66_fu_348;

assign local_reference_V_2_2_21_out = local_reference_V_1_74_fu_380;

assign local_reference_V_2_3_21_out = local_reference_V_1_78_fu_396;

assign local_reference_V_2_4_21_out = local_reference_V_1_82_fu_412;

assign local_reference_V_2_5_21_out = local_reference_V_1_86_fu_428;

assign local_reference_V_2_6_21_out = local_reference_V_1_90_fu_444;

assign local_reference_V_2_7_21_out = local_reference_V_1_94_fu_460;

assign local_reference_V_2_8_21_out = local_reference_V_1_98_fu_476;

assign local_reference_V_2_9_21_out = local_reference_V_1_102_fu_492;

assign local_reference_V_3_10_21_out = local_reference_V_1_107_fu_512;

assign local_reference_V_3_11_21_out = local_reference_V_1_111_fu_528;

assign local_reference_V_3_12_21_out = local_reference_V_1_115_fu_544;

assign local_reference_V_3_13_21_out = local_reference_V_1_119_fu_560;

assign local_reference_V_3_14_21_out = local_reference_V_1_123_fu_576;

assign local_reference_V_3_15_21_out = local_reference_V_1_127_fu_592;

assign local_reference_V_3_1_21_out = local_reference_V_1_71_fu_368;

assign local_reference_V_3_21_out = local_reference_V_1_67_fu_352;

assign local_reference_V_3_2_21_out = local_reference_V_1_75_fu_384;

assign local_reference_V_3_3_21_out = local_reference_V_1_79_fu_400;

assign local_reference_V_3_4_21_out = local_reference_V_1_83_fu_416;

assign local_reference_V_3_5_21_out = local_reference_V_1_87_fu_432;

assign local_reference_V_3_6_21_out = local_reference_V_1_91_fu_448;

assign local_reference_V_3_7_21_out = local_reference_V_1_95_fu_464;

assign local_reference_V_3_8_21_out = local_reference_V_1_99_fu_480;

assign local_reference_V_3_9_21_out = local_reference_V_1_103_fu_496;

assign reference_string_comp_3_address0 = zext_ln94_fu_1787_p1;

assign trunc_ln94_fu_1802_p1 = ap_sig_allocacmp_i_2[3:0];

assign xor_ln94_fu_1781_p2 = (ap_sig_allocacmp_i_2 ^ 7'd64);

assign zext_ln94_fu_1787_p1 = xor_ln94_fu_1781_p2;

endmodule //seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_326
