-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity seq_align_multiple_seq_align_Pipeline_VITIS_LOOP_538_11 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    query_string_comp_0_TVALID : IN STD_LOGIC;
    empty_23 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_24 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_25 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_26 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_27 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_28 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_29 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_30 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_31 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_32 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_33 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_34 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_35 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_36 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_37 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_38 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_39 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_40 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_41 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_42 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_43 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_44 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_45 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_46 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_47 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_48 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_49 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_50 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_51 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_52 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (7 downto 0);
    query_string_comp_0_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    query_string_comp_0_TREADY : OUT STD_LOGIC;
    query_data_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_1_out_ap_vld : OUT STD_LOGIC;
    query_data_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_2_out_ap_vld : OUT STD_LOGIC;
    query_data_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_3_out_ap_vld : OUT STD_LOGIC;
    query_data_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_4_out_ap_vld : OUT STD_LOGIC;
    query_data_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_5_out_ap_vld : OUT STD_LOGIC;
    query_data_6_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_6_out_ap_vld : OUT STD_LOGIC;
    query_data_7_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_7_out_ap_vld : OUT STD_LOGIC;
    query_data_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_8_out_ap_vld : OUT STD_LOGIC;
    query_data_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_9_out_ap_vld : OUT STD_LOGIC;
    query_data_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_10_out_ap_vld : OUT STD_LOGIC;
    query_data_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_11_out_ap_vld : OUT STD_LOGIC;
    query_data_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_12_out_ap_vld : OUT STD_LOGIC;
    query_data_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_13_out_ap_vld : OUT STD_LOGIC;
    query_data_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_14_out_ap_vld : OUT STD_LOGIC;
    query_data_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_15_out_ap_vld : OUT STD_LOGIC;
    query_data_16_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_16_out_ap_vld : OUT STD_LOGIC;
    query_data_17_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_17_out_ap_vld : OUT STD_LOGIC;
    query_data_18_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_18_out_ap_vld : OUT STD_LOGIC;
    query_data_19_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_19_out_ap_vld : OUT STD_LOGIC;
    query_data_20_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_20_out_ap_vld : OUT STD_LOGIC;
    query_data_21_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_21_out_ap_vld : OUT STD_LOGIC;
    query_data_22_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_22_out_ap_vld : OUT STD_LOGIC;
    query_data_23_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_23_out_ap_vld : OUT STD_LOGIC;
    query_data_24_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_24_out_ap_vld : OUT STD_LOGIC;
    query_data_25_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_25_out_ap_vld : OUT STD_LOGIC;
    query_data_26_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_26_out_ap_vld : OUT STD_LOGIC;
    query_data_27_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_27_out_ap_vld : OUT STD_LOGIC;
    query_data_28_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_28_out_ap_vld : OUT STD_LOGIC;
    query_data_29_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_29_out_ap_vld : OUT STD_LOGIC;
    query_data_30_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_30_out_ap_vld : OUT STD_LOGIC;
    query_data_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    query_data_out_ap_vld : OUT STD_LOGIC;
    p_phi_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_phi_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of seq_align_multiple_seq_align_Pipeline_VITIS_LOOP_538_11 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln538_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal query_string_comp_0_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal query_data_31_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_168 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_2_fu_1005_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal query_data_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_30_fu_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_29_fu_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_28_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_27_fu_188 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_26_fu_192 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_25_fu_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_24_fu_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_23_fu_204 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_22_fu_208 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_21_fu_212 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_20_fu_216 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_19_fu_220 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_18_fu_224 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_17_fu_228 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_16_fu_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_15_fu_236 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_14_fu_240 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_13_fu_244 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_12_fu_248 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_11_fu_252 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_10_fu_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_9_fu_260 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_8_fu_264 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_7_fu_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_6_fu_272 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_5_fu_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_4_fu_280 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_3_fu_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_2_fu_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal query_data_1_fu_292 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component seq_align_multiple_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component seq_align_multiple_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_168 <= ap_const_lv6_0;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_168 <= i_2_fu_1005_p2;
                end if;
            end if; 
        end if;
    end process;

    query_data_10_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_10_fu_256 <= empty_32;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_10_fu_256 <= query_data_9_fu_260;
                end if;
            end if; 
        end if;
    end process;

    query_data_11_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_11_fu_252 <= empty_33;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_11_fu_252 <= query_data_10_fu_256;
                end if;
            end if; 
        end if;
    end process;

    query_data_12_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_12_fu_248 <= empty_34;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_12_fu_248 <= query_data_11_fu_252;
                end if;
            end if; 
        end if;
    end process;

    query_data_13_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_13_fu_244 <= empty_35;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_13_fu_244 <= query_data_12_fu_248;
                end if;
            end if; 
        end if;
    end process;

    query_data_14_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_14_fu_240 <= empty_36;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_14_fu_240 <= query_data_13_fu_244;
                end if;
            end if; 
        end if;
    end process;

    query_data_15_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_15_fu_236 <= empty_37;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_15_fu_236 <= query_data_14_fu_240;
                end if;
            end if; 
        end if;
    end process;

    query_data_16_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_16_fu_232 <= empty_38;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_16_fu_232 <= query_data_15_fu_236;
                end if;
            end if; 
        end if;
    end process;

    query_data_17_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_17_fu_228 <= empty_39;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_17_fu_228 <= query_data_16_fu_232;
                end if;
            end if; 
        end if;
    end process;

    query_data_18_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_18_fu_224 <= empty_40;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_18_fu_224 <= query_data_17_fu_228;
                end if;
            end if; 
        end if;
    end process;

    query_data_19_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_19_fu_220 <= empty_41;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_19_fu_220 <= query_data_18_fu_224;
                end if;
            end if; 
        end if;
    end process;

    query_data_1_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_1_fu_292 <= empty_23;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_1_fu_292 <= query_string_comp_0_TDATA;
                end if;
            end if; 
        end if;
    end process;

    query_data_20_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_20_fu_216 <= empty_42;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_20_fu_216 <= query_data_19_fu_220;
                end if;
            end if; 
        end if;
    end process;

    query_data_21_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_21_fu_212 <= empty_43;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_21_fu_212 <= query_data_20_fu_216;
                end if;
            end if; 
        end if;
    end process;

    query_data_22_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_22_fu_208 <= empty_44;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_22_fu_208 <= query_data_21_fu_212;
                end if;
            end if; 
        end if;
    end process;

    query_data_23_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_23_fu_204 <= empty_45;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_23_fu_204 <= query_data_22_fu_208;
                end if;
            end if; 
        end if;
    end process;

    query_data_24_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_24_fu_200 <= empty_46;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_24_fu_200 <= query_data_23_fu_204;
                end if;
            end if; 
        end if;
    end process;

    query_data_25_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_25_fu_196 <= empty_47;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_25_fu_196 <= query_data_24_fu_200;
                end if;
            end if; 
        end if;
    end process;

    query_data_26_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_26_fu_192 <= empty_48;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_26_fu_192 <= query_data_25_fu_196;
                end if;
            end if; 
        end if;
    end process;

    query_data_27_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_27_fu_188 <= empty_49;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_27_fu_188 <= query_data_26_fu_192;
                end if;
            end if; 
        end if;
    end process;

    query_data_28_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_28_fu_184 <= empty_50;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_28_fu_184 <= query_data_27_fu_188;
                end if;
            end if; 
        end if;
    end process;

    query_data_29_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_29_fu_180 <= empty_51;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_29_fu_180 <= query_data_28_fu_184;
                end if;
            end if; 
        end if;
    end process;

    query_data_2_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_2_fu_288 <= empty_24;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_2_fu_288 <= query_data_1_fu_292;
                end if;
            end if; 
        end if;
    end process;

    query_data_30_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_30_fu_176 <= empty_52;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_30_fu_176 <= query_data_29_fu_180;
                end if;
            end if; 
        end if;
    end process;

    query_data_3_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_3_fu_284 <= empty_25;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_3_fu_284 <= query_data_2_fu_288;
                end if;
            end if; 
        end if;
    end process;

    query_data_4_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_4_fu_280 <= empty_26;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_4_fu_280 <= query_data_3_fu_284;
                end if;
            end if; 
        end if;
    end process;

    query_data_5_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_5_fu_276 <= empty_27;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_5_fu_276 <= query_data_4_fu_280;
                end if;
            end if; 
        end if;
    end process;

    query_data_6_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_6_fu_272 <= empty_28;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_6_fu_272 <= query_data_5_fu_276;
                end if;
            end if; 
        end if;
    end process;

    query_data_7_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_7_fu_268 <= empty_29;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_7_fu_268 <= query_data_6_fu_272;
                end if;
            end if; 
        end if;
    end process;

    query_data_8_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_8_fu_264 <= empty_30;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_8_fu_264 <= query_data_7_fu_268;
                end if;
            end if; 
        end if;
    end process;

    query_data_9_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_9_fu_260 <= empty_31;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_9_fu_260 <= query_data_8_fu_264;
                end if;
            end if; 
        end if;
    end process;

    query_data_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    query_data_fu_172 <= empty;
                elsif (((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    query_data_fu_172 <= query_data_30_fu_176;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                query_data_31_fu_164 <= query_data_fu_172;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, query_string_comp_0_TVALID, icmp_ln538_fu_999_p2)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (query_string_comp_0_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, query_string_comp_0_TVALID, icmp_ln538_fu_999_p2)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (query_string_comp_0_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, query_string_comp_0_TVALID, icmp_ln538_fu_999_p2)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (query_string_comp_0_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(query_string_comp_0_TVALID, icmp_ln538_fu_999_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (query_string_comp_0_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_1005_p2 <= std_logic_vector(unsigned(i_fu_168) + unsigned(ap_const_lv6_1));
    icmp_ln538_fu_999_p2 <= "1" when (i_fu_168 = ap_const_lv6_20) else "0";
    p_phi_out <= query_data_31_fu_164;

    p_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_10_out <= query_data_10_fu_256;

    query_data_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_10_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_11_out <= query_data_11_fu_252;

    query_data_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_11_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_12_out <= query_data_12_fu_248;

    query_data_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_12_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_13_out <= query_data_13_fu_244;

    query_data_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_13_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_14_out <= query_data_14_fu_240;

    query_data_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_14_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_15_out <= query_data_15_fu_236;

    query_data_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_15_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_16_out <= query_data_16_fu_232;

    query_data_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_16_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_17_out <= query_data_17_fu_228;

    query_data_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_17_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_18_out <= query_data_18_fu_224;

    query_data_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_18_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_19_out <= query_data_19_fu_220;

    query_data_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_19_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_1_out <= query_data_1_fu_292;

    query_data_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_1_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_20_out <= query_data_20_fu_216;

    query_data_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_20_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_21_out <= query_data_21_fu_212;

    query_data_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_21_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_22_out <= query_data_22_fu_208;

    query_data_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_22_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_23_out <= query_data_23_fu_204;

    query_data_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_23_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_24_out <= query_data_24_fu_200;

    query_data_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_24_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_25_out <= query_data_25_fu_196;

    query_data_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_25_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_26_out <= query_data_26_fu_192;

    query_data_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_26_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_27_out <= query_data_27_fu_188;

    query_data_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_27_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_28_out <= query_data_28_fu_184;

    query_data_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_28_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_29_out <= query_data_29_fu_180;

    query_data_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_29_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_2_out <= query_data_2_fu_288;

    query_data_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_2_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_30_out <= query_data_30_fu_176;

    query_data_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_30_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_3_out <= query_data_3_fu_284;

    query_data_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_3_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_4_out <= query_data_4_fu_280;

    query_data_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_4_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_5_out <= query_data_5_fu_276;

    query_data_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_5_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_6_out <= query_data_6_fu_272;

    query_data_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_6_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_7_out <= query_data_7_fu_268;

    query_data_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_7_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_8_out <= query_data_8_fu_264;

    query_data_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_8_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_9_out <= query_data_9_fu_260;

    query_data_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_9_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    query_data_out <= query_data_fu_172;

    query_data_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_data_out_ap_vld <= ap_const_logic_1;
        else 
            query_data_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    query_string_comp_0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, query_string_comp_0_TVALID, icmp_ln538_fu_999_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_string_comp_0_TDATA_blk_n <= query_string_comp_0_TVALID;
        else 
            query_string_comp_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    query_string_comp_0_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln538_fu_999_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln538_fu_999_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_string_comp_0_TREADY <= ap_const_logic_1;
        else 
            query_string_comp_0_TREADY <= ap_const_logic_0;
        end if; 
    end process;

end behav;
