set SynModuleInfo {
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_2 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_2 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_2
    SUBMODULES {
      {MODELNAME seq_align_multiple_flow_control_loop_pipe_sequential_init RTLNAME seq_align_multiple_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME seq_align_multiple_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_3 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_3 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_3}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel1 MODELNAME seq_align_multiple_Pipeline_kernel_kernel1 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel1
    SUBMODULES {
      {MODELNAME seq_align_multiple_mux_42_2_1_1 RTLNAME seq_align_multiple_mux_42_2_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME seq_align_multiple_mux_164_2_1_1 RTLNAME seq_align_multiple_mux_164_2_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe2 MODELNAME seq_align_multiple_Pipeline_pe1_pe2 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe2
    SUBMODULES {
      {MODELNAME seq_align_multiple_mux_164_9_1_1 RTLNAME seq_align_multiple_mux_164_9_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_21 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_21 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_21}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_32 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_32 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_32}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel13 MODELNAME seq_align_multiple_Pipeline_kernel_kernel13 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel13}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe24 MODELNAME seq_align_multiple_Pipeline_pe1_pe24 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe24}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_25 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_25 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_25}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_36 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_36 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_36}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel17 MODELNAME seq_align_multiple_Pipeline_kernel_kernel17 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel17}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe28 MODELNAME seq_align_multiple_Pipeline_pe1_pe28 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe28}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_29 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_29 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_29}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_310 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_310 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_310}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel111 MODELNAME seq_align_multiple_Pipeline_kernel_kernel111 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel111}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe212 MODELNAME seq_align_multiple_Pipeline_pe1_pe212 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe212}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_213 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_213 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_213}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_314 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_314 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_314}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel115 MODELNAME seq_align_multiple_Pipeline_kernel_kernel115 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel115}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe216 MODELNAME seq_align_multiple_Pipeline_pe1_pe216 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe216}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_217 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_217 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_217}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_318 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_318 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_318}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel119 MODELNAME seq_align_multiple_Pipeline_kernel_kernel119 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel119}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe220 MODELNAME seq_align_multiple_Pipeline_pe1_pe220 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe220}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_221 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_221 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_221}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_322 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_322 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_322}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel123 MODELNAME seq_align_multiple_Pipeline_kernel_kernel123 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel123}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe224 MODELNAME seq_align_multiple_Pipeline_pe1_pe224 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe224}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_225 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_225 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_75_1_VITIS_LOOP_76_225}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_326 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_93_326 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_93_326}
  {SRCNAME seq_align_multiple_Pipeline_kernel_kernel127 MODELNAME seq_align_multiple_Pipeline_kernel_kernel127 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_kernel_kernel127}
  {SRCNAME seq_align_multiple_Pipeline_pe1_pe228 MODELNAME seq_align_multiple_Pipeline_pe1_pe228 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_pe1_pe228}
  {SRCNAME seq_align_multiple_Pipeline_VITIS_LOOP_286_2 MODELNAME seq_align_multiple_Pipeline_VITIS_LOOP_286_2 RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_286_2
    SUBMODULES {
      {MODELNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_286_2_dummies_inner_V_RAM_AUTO_1R1W RTLNAME seq_align_multiple_seq_align_multiple_Pipeline_VITIS_LOOP_286_2_dummies_inner_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME seq_align_multiple MODELNAME seq_align_multiple RTLNAME seq_align_multiple IS_TOP 1
    SUBMODULES {
      {MODELNAME seq_align_multiple_dp_matrix_V_RAM_AUTO_1R1W RTLNAME seq_align_multiple_dp_matrix_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
