// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module seq_align_multiple_seq_align_global_Pipeline_VITIS_LOOP_1025_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        last_pe_score_address0,
        last_pe_score_ce0,
        last_pe_score_we0,
        last_pe_score_d0,
        last_pe_scoreIx_address0,
        last_pe_scoreIx_ce0,
        last_pe_scoreIx_we0,
        last_pe_scoreIx_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] last_pe_score_address0;
output   last_pe_score_ce0;
output   last_pe_score_we0;
output  [31:0] last_pe_score_d0;
output  [7:0] last_pe_scoreIx_address0;
output   last_pe_scoreIx_ce0;
output   last_pe_scoreIx_we0;
output  [31:0] last_pe_scoreIx_d0;

reg ap_idle;
reg last_pe_score_ce0;
reg last_pe_score_we0;
reg last_pe_scoreIx_ce0;
reg last_pe_scoreIx_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln1025_fu_70_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] ip_cast_fu_82_p1;
reg   [8:0] ip_fu_32;
wire   [8:0] add_ln1025_fu_76_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_ip_1;
wire  signed [31:0] sext_ln1028_fu_102_p1;
wire   [7:0] trunc_ln1028_fu_88_p1;
wire   [9:0] zext_ln1028_fu_92_p1;
wire   [9:0] sub_ln1028_fu_96_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

seq_align_multiple_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln1025_fu_70_p2 == 1'd0)) begin
            ip_fu_32 <= add_ln1025_fu_76_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ip_fu_32 <= 9'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1025_fu_70_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_ip_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_ip_1 = ip_fu_32;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        last_pe_scoreIx_ce0 = 1'b1;
    end else begin
        last_pe_scoreIx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1025_fu_70_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        last_pe_scoreIx_we0 = 1'b1;
    end else begin
        last_pe_scoreIx_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        last_pe_score_ce0 = 1'b1;
    end else begin
        last_pe_score_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1025_fu_70_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        last_pe_score_we0 = 1'b1;
    end else begin
        last_pe_score_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1025_fu_76_p2 = (ap_sig_allocacmp_ip_1 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln1025_fu_70_p2 = ((ap_sig_allocacmp_ip_1 == 9'd256) ? 1'b1 : 1'b0);

assign ip_cast_fu_82_p1 = ap_sig_allocacmp_ip_1;

assign last_pe_scoreIx_address0 = ip_cast_fu_82_p1;

assign last_pe_scoreIx_d0 = sext_ln1028_fu_102_p1;

assign last_pe_score_address0 = ip_cast_fu_82_p1;

assign last_pe_score_d0 = sext_ln1028_fu_102_p1;

assign sext_ln1028_fu_102_p1 = $signed(sub_ln1028_fu_96_p2);

assign sub_ln1028_fu_96_p2 = ($signed(10'd1017) - $signed(zext_ln1028_fu_92_p1));

assign trunc_ln1028_fu_88_p1 = ap_sig_allocacmp_ip_1[7:0];

assign zext_ln1028_fu_92_p1 = trunc_ln1028_fu_88_p1;

endmodule //seq_align_multiple_seq_align_global_Pipeline_VITIS_LOOP_1025_3
